<a href="https://colab.research.google.com/github/cod3astro/ML_practice/blob/main/codon_usage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

In [2]:
df = pd.read_csv('codon_usage.csv', index_col='SpeciesID')
df.drop_duplicates(inplace=True)
df.head()

/tmp/ipython-input-2-2076267449.py:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('codon_usage.csv', index_col='SpeciesID')


Kingdom  DNAtype  Ncodons                              SpeciesName  \
SpeciesID                                                                      
100217        vrl        0     1995  Epizootic haematopoietic necrosis virus   
100220        vrl        0     1474                         Bohle iridovirus   
100755        vrl        0     4862             Sweet potato leaf curl virus   
100880        vrl        0     1915             Northern cereal mosaic virus   
100887        vrl        0    22831           Soil-borne cereal mosaic virus   

               UUU      UUC      UUA      UUG      CUU      CUC  ...      CGG  \
SpeciesID                                                        ...            
100217     0.01654  0.01203  0.00050  0.00351  0.01203  0.03208  ...  0.00451   
100220     0.02714  0.01357  0.00068  0.00678  0.00407  0.02849  ...  0.00136   
100755     0.01974   0.0218  0.01357  0.01543  0.00782  0.01111  ...  0.00596   
100880     0.01775  0.02245  0.01619  0.00992  0.01567  0.01358  ...  0.00366   
100887     0.02816  0.01371  0.00767  0.03679  0.01380  0.00548  ...  0.00604   

               AGA      AGG      GAU      GAC      GAA      GAG      UAA  \
SpeciesID                                                                  
100217     0.01303  0.03559  0.01003  0.04612  0.01203  0.04361  0.00251   
100220     0.01696  0.03596  0.01221  0.04545  0.01560  0.04410  0.00271   
100755     0.01974  0.02489  0.03126  0.02036  0.02242  0.02468  0.00391   
100880     0.01410  0.01671  0.03760  0.01932  0.03029  0.03446  0.00261   
100887     0.01494  0.01734  0.04148  0.02483  0.03359  0.03679  0.00000   

               UAG      UGA  
SpeciesID                    
100217     0.00050  0.00000  
100220     0.00068  0.00000  
100755     0.00000  0.00144  
100880     0.00157  0.00000  
100887     0.00044  0.00131  

[5 rows x 68 columns]

In [3]:
df.shape

(13028, 68)

In [4]:
df.columns

Index(['Kingdom', 'DNAtype', 'Ncodons', 'SpeciesName', 'UUU', 'UUC', 'UUA',
       'UUG', 'CUU', 'CUC', 'CUA', 'CUG', 'AUU', 'AUC', 'AUA', 'AUG', 'GUU',
       'GUC', 'GUA', 'GUG', 'GCU', 'GCC', 'GCA', 'GCG', 'CCU', 'CCC', 'CCA',
       'CCG', 'UGG', 'GGU', 'GGC', 'GGA', 'GGG', 'UCU', 'UCC', 'UCA', 'UCG',
       'AGU', 'AGC', 'ACU', 'ACC', 'ACA', 'ACG', 'UAU', 'UAC', 'CAA', 'CAG',
       'AAU', 'AAC', 'UGU', 'UGC', 'CAU', 'CAC', 'AAA', 'AAG', 'CGU', 'CGC',
       'CGA', 'CGG', 'AGA', 'AGG', 'GAU', 'GAC', 'GAA', 'GAG', 'UAA', 'UAG',
       'UGA'],
      dtype='object')

In [5]:
df.isnull().any().sum()

np.int64(0)

In [6]:
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.feature_selection import mutual_info_classif
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score, confusion_matrix
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder, LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.impute import SimpleImputer
from imblearn.over_sampling import SMOTE

In [7]:
features = ['DNAtype', 'UUA',
       'UUG', 'CUU', 'CUC', 'CUA', 'CUG', 'AUU', 'AUC', 'AUA', 'AUG', 'GUU',
       'GUC', 'GUA', 'GUG', 'GCU', 'GCC', 'GCA', 'GCG', 'CCU', 'CCC', 'CCA',
       'CCG', 'UGG', 'GGU', 'GGC', 'GGA', 'GGG', 'UCU', 'UCC', 'UCA', 'UCG',
       'AGU', 'AGC', 'ACU', 'ACC', 'ACA', 'ACG', 'UAU', 'UAC', 'CAA', 'CAG',
       'AAU', 'AAC', 'UGU', 'UGC', 'CAU', 'CAC', 'AAA', 'AAG', 'CGU', 'CGC',
       'CGA', 'CGG', 'AGA', 'AGG', 'GAU', 'GAC', 'GAA', 'GAG', 'UAA', 'UAG',
       'UGA']
mi_features = ['DNAtype', 'Ncodons', 'UUU', 'UUC']
target = 'Kingdom'
X = df[features]
y = df[target]
smote = SMOTE(random_state=42)
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state=42, stratify=y, test_size=0.2)

In [8]:
Features = ['DNAtype', 'Ncodons', 'SpeciesName', 'UUU', 'UUC', 'UUA',
       'UUG', 'CUU', 'CUC', 'CUA', 'CUG', 'AUU', 'AUC', 'AUA', 'AUG', 'GUU',
       'GUC', 'GUA', 'GUG', 'GCU', 'GCC', 'GCA', 'GCG', 'CCU', 'CCC', 'CCA',
       'CCG', 'UGG', 'GGU', 'GGC', 'GGA', 'GGG', 'UCU', 'UCC', 'UCA', 'UCG',
       'AGU', 'AGC', 'ACU', 'ACC', 'ACA', 'ACG', 'UAU', 'UAC', 'CAA', 'CAG',
       'AAU', 'AAC', 'UGU', 'UGC', 'CAU', 'CAC', 'AAA', 'AAG', 'CGU', 'CGC',
       'CGA', 'CGG', 'AGA', 'AGG', 'GAU', 'GAC', 'GAA', 'GAG', 'UAA', 'UAG',
       'UGA']
Target = 'Kingdom'
a = df[Features]
b = df[Target]
train_a, val_a, train_b, val_b = train_test_split(a, b, random_state=42, stratify=b, test_size=0.2)

In [9]:
for col in X:
  if X[col].dtype == 'object':
    print(col)

In [10]:
for col in X.columns:
    if X[col].dtype == 'object':
        # Find rows with non-numeric values
        non_numeric = X[col][~X[col].apply(lambda x: str(x).replace(';', '').isdigit())]
        if not non_numeric.empty:
            print(f"Column '{col}' has non-numeric values:")
            print(non_numeric.unique())

In [11]:
for col in X.columns:
    # Check if any value is a string that can't convert to float
    non_float = []
    for val in X[col]:
        try:
            float(val)
        except (ValueError, TypeError):
            non_float.append(val)

    if non_float:
        print(f"Column '{col}' has non-float values:")
        print(pd.Series(non_float).unique())

In [12]:
print("train_X dtypes:", train_X.dtypes)
print("val_X dtypes:", val_X.dtypes)

train_X dtypes: DNAtype      int64
UUA        float64
UUG        float64
CUU        float64
CUC        float64
            ...   
GAA        float64
GAG        float64
UAA        float64
UAG        float64
UGA        float64
Length: 63, dtype: object
val_X dtypes: DNAtype      int64
UUA        float64
UUG        float64
CUU        float64
CUC        float64
            ...   
GAA        float64
GAG        float64
UAA        float64
UAG        float64
UGA        float64
Length: 63, dtype: object


In [13]:
copy_X = X.copy()
copy_y = y.copy()
for col in copy_X.select_dtypes('float'):
    copy_X[col] = copy_X[col].round().astype(int)
for char in copy_X.select_dtypes('object'):
  copy_X.loc[:, char], _ = copy_X[char].factorize()
discrete_values = copy_X.dtypes == int
copy_y, _ = pd.factorize(y)

def make_mi_score(copy_X, copy_y, discrete_values):
    mi_scores = mutual_info_classif(copy_X, copy_y, discrete_features=discrete_values)
    mi_scores = pd.Series(mi_scores, name='MI SCORES', index=copy_X.columns)
    mi_scores = mi_scores.sort_values(ascending=False)
    return mi_scores

mi_scores = make_mi_score(copy_X, copy_y, discrete_values)
mi_scores[:7]

DNAtype    0.403521
UUA        0.000000
UUG        0.000000
CUU        0.000000
CUC        0.000000
CUA        0.000000
CUG        0.000000
Name: MI SCORES, dtype: float64

In [14]:
y.value_counts(normalize=True)

Kingdom
bct    0.224133
vrl    0.217378
pln    0.193660
vrt    0.159426
inv    0.103239
mam    0.043905
phg    0.016887
rod    0.016503
pri    0.013816
arc    0.009671
plm    0.001382
Name: proportion, dtype: float64

In [15]:
X_resampled, y_resampled = smote.fit_resample(X, y)
X_train, X_val, y_train, y_val = train_test_split(X_resampled, y_resampled, random_state=42, stratify=y_resampled, test_size=0.2)

In [16]:
model = Pipeline([
    ('model', XGBClassifier(random_state=42, eval_metric='mlogloss', n_estimators=300, max_depth=7, learning_rate=0.13))
])
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_val_encoded = label_encoder.transform(y_val)

model.fit(X_train, y_train_encoded)
xgb_train_preds_encoded = model.predict(X_val)
xgb_train_preds = label_encoder.inverse_transform(xgb_train_preds_encoded)
print("Accuracy:", accuracy_score(y_val, xgb_train_preds))
print("Precision:", precision_score(y_val, xgb_train_preds, average='macro'))
print("Recall:", recall_score(y_val, xgb_train_preds, average='macro'))
print("F1 Score:", f1_score(y_val, xgb_train_preds, average='macro'))
print("Confusion Matrix:\n", confusion_matrix(y_val, xgb_train_preds))

Accuracy: 0.9834993773349938
Precision: 0.9835438942196021
Recall: 0.9834993773349939
F1 Score: 0.9834660372409999
Confusion Matrix:
 [[584   0   0   0   0   0   0   0   0   0   0]
 [  7 553   5   0  11   1   4   0   0   3   0]
 [  0   1 566   0   0   0   9   0   0   5   3]
 [  0   0   0 583   0   0   0   1   0   0   0]
 [  0   0   0   0 584   0   0   0   0   0   0]
 [  0   0   0   0   0 584   0   0   0   0   0]
 [  0   7   8   0   0   0 562   0   0   7   0]
 [  0   0   0   0   0   0   0 583   1   0   0]
 [  0   0   1   1   0   0   0   0 582   0   0]
 [  1   1   8   0   1   0   7   0   0 566   0]
 [  0   1   5   2   0   0   0   2   0   3 571]]


In [17]:
scores = cross_val_score(
    RandomForestClassifier(),
    X[['DNAtype']].apply(lambda x: pd.factorize(x)[0]),  # Convert to numeric
    y,
    cv=5
)
print(f"Accuracy using only DNAtype: {scores.mean():.2f}")

Accuracy using only DNAtype: 0.41


In [18]:
# 1. Target Encoder
class TargetEncoder(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.encoder = LabelEncoder()

    def fit(self, y):
        self.encoder.fit(y)
        return self

    def transform(self, y):
        return self.encoder.transform(y)

    def inverse_transform(self, y):
        return self.encoder.inverse_transform(y)

# 2. Data Cleaner
class DataCleaner(BaseEstimator, TransformerMixin):
    def __init__(self, columns_to_drop=None, numeric_features=None,
                ordinal_features=None, one_hot_features=None):
        self.columns_to_drop = columns_to_drop or []
        self.numeric_features = numeric_features or []
        self.ordinal_features = ordinal_features or []
        self.one_hot_features = one_hot_features or []

    def fit(self, X, y=None):
        self.existing_num_ = [col for col in self.numeric_features if col in X.columns]
        self.existing_cat_ = [col for col in
                            (self.one_hot_features + self.ordinal_features)
                            if col in X.columns]

        if self.existing_num_:
            self.num_means_ = X[self.existing_num_].mean()
        if self.existing_cat_:
            self.cat_modes_ = X[self.existing_cat_].mode().iloc[0]
        return self

    def transform(self, X):
        X_clean = X.copy()
        cols_to_drop = [col for col in self.columns_to_drop if col in X_clean.columns]
        X_clean = X_clean.drop(columns=cols_to_drop, errors='ignore')

        if hasattr(self, 'num_means_'):
            X_clean[self.existing_num_] = X_clean[self.existing_num_].fillna(self.num_means_)
        if hasattr(self, 'cat_modes_'):
            X_clean[self.existing_cat_] = X_clean[self.existing_cat_].fillna(self.cat_modes_)

        str_cols = X_clean.select_dtypes(include=['object']).columns
        for col in str_cols:
            X_clean[col] = X_clean[col].astype(str).str.strip().str.lower()

        return X_clean

# 3. Pipeline Builder
def build_pipeline(**kwargs):
    numeric_features = kwargs.get('numeric_features', [])
    one_hot_features = kwargs.get('one_hot_features', [])
    ordinal_features = kwargs.get('ordinal_features', [])

    transformers = []
    if numeric_features:
        transformers.append(('num', Pipeline([('scaler', StandardScaler())]), numeric_features))
    if one_hot_features:
        transformers.append(('cat', Pipeline([('onehot', OneHotEncoder(handle_unknown='ignore'))]), one_hot_features))
    if ordinal_features:
        transformers.append(('ord', Pipeline([('ordinal', OrdinalEncoder())]), ordinal_features))

    preprocessor = ColumnTransformer(transformers) if transformers else None

    steps = [('cleaner', DataCleaner(**kwargs))]
    if preprocessor:
        steps.append(('preprocessor', preprocessor))
    steps.append(('classifier', XGBClassifier(
        random_state=42,
        n_estimators=300,
        max_depth=7,
        learning_rate=0.13,
        eval_metric='mlogloss'
    )))

    return Pipeline(steps)

# 4. Training Function
def train_and_save_model(X_train, y_train, save_path='model.joblib', **kwargs):
    # Encode target
    target_encoder = TargetEncoder()
    y_encoded = target_encoder.fit_transform(y_train)

    # Build and train pipeline
    pipeline = build_pipeline(**kwargs)
    pipeline.fit(X_train, y_encoded)

    # Save both components
    joblib.dump({
        'pipeline': pipeline,
        'target_encoder': target_encoder
    }, save_path)

    print(f"\n✅ Model successfully saved to {save_path}")
    print(f"Model contains: {', '.join([step[0] for step in pipeline.steps])}")
    print(f"Target classes: {list(target_encoder.encoder.classes_)}")

    return pipeline, target_encoder

if __name__ == "__main__":
    # Load your data
    data = pd.read_csv('codon_usage.csv', low_memory=False)

    # Handle mixed-type columns
    for col in [5, 6]:
        data.iloc[:, col] = pd.to_numeric(data.iloc[:, col], errors='coerce')

    # Split data
    TARGET_COL = 'Kingdom'
    X = data.drop(columns=[TARGET_COL])
    y = data[TARGET_COL]

    # Train and save
    pipeline, encoder = train_and_save_model(
        X_train=X,
        y_train=y,
        save_path='species_model.joblib',
        columns_to_drop=['SpeciesName', 'UUU', 'UUC', 'Ncodons'],
        numeric_features=[],
        one_hot_features=[],
        ordinal_features=[]
    )


✅ Model successfully saved to species_model.joblib
Model contains: cleaner, classifier
Target classes: ['arc', 'bct', 'inv', 'mam', 'phg', 'plm', 'pln', 'pri', 'rod', 'vrl', 'vrt']


In [19]:
from google.colab import files

files.download('species_model.joblib')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
def load_and_predict(model_path, new_data_path):
    # Load model components
    model_data = joblib.load(model_path)
    pipeline = model_data['pipeline']
    target_encoder = model_data['target_encoder']

    # Load new data
    new_data = pd.read_csv(new_data_path)

    # Make predictions
    encoded_preds = pipeline.predict(new_data)
    predictions = target_encoder.inverse_transform(encoded_preds)

    # Create output DataFrame
    results = pd.DataFrame({
        'Predicted_Class': predictions,
        'Encoded_Value': encoded_preds
    })

    print("\n🎯 Prediction Results:")
    print(results.head())

    # Save predictions
    results.to_csv('predictions.csv', index=False)
    print(f"\n✅ Predictions saved to predictions.csv")

    return results

if __name__ == "__main__":
    # Example usage
    predictions = load_and_predict(
        model_path='species_model.joblib',
        new_data_path='codon_usage.csv'
    )

In [ ]:
# Check shapes before and after cleaning
print("Original shape:", data.shape)
cleaned_data = pipeline.named_steps['cleaner'].transform(data)
print("Cleaned shape:", cleaned_data.shape)

In [ ]:
data.info()
data.head()