In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('codon_usage.csv', index_col='SpeciesID')
df.head()

/tmp/ipython-input-4-459728373.py:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('codon_usage.csv', index_col='SpeciesID')


Kingdom  DNAtype  Ncodons                              SpeciesName  \
SpeciesID                                                                      
100217        vrl        0     1995  Epizootic haematopoietic necrosis virus   
100220        vrl        0     1474                         Bohle iridovirus   
100755        vrl        0     4862             Sweet potato leaf curl virus   
100880        vrl        0     1915             Northern cereal mosaic virus   
100887        vrl        0    22831           Soil-borne cereal mosaic virus   

               UUU      UUC      UUA      UUG      CUU      CUC  ...      CGG  \
SpeciesID                                                        ...            
100217     0.01654  0.01203  0.00050  0.00351  0.01203  0.03208  ...  0.00451   
100220     0.02714  0.01357  0.00068  0.00678  0.00407  0.02849  ...  0.00136   
100755     0.01974   0.0218  0.01357  0.01543  0.00782  0.01111  ...  0.00596   
100880     0.01775  0.02245  0.01619  0.00992  0.01567  0.01358  ...  0.00366   
100887     0.02816  0.01371  0.00767  0.03679  0.01380  0.00548  ...  0.00604   

               AGA      AGG      GAU      GAC      GAA      GAG      UAA  \
SpeciesID                                                                  
100217     0.01303  0.03559  0.01003  0.04612  0.01203  0.04361  0.00251   
100220     0.01696  0.03596  0.01221  0.04545  0.01560  0.04410  0.00271   
100755     0.01974  0.02489  0.03126  0.02036  0.02242  0.02468  0.00391   
100880     0.01410  0.01671  0.03760  0.01932  0.03029  0.03446  0.00261   
100887     0.01494  0.01734  0.04148  0.02483  0.03359  0.03679  0.00000   

               UAG      UGA  
SpeciesID                    
100217     0.00050  0.00000  
100220     0.00068  0.00000  
100755     0.00000  0.00144  
100880     0.00157  0.00000  
100887     0.00044  0.00131  

[5 rows x 68 columns]

In [6]:
df.shape

(13028, 68)

In [8]:
df.columns

Index(['Kingdom', 'DNAtype', 'Ncodons', 'SpeciesName', 'UUU', 'UUC', 'UUA',
       'UUG', 'CUU', 'CUC', 'CUA', 'CUG', 'AUU', 'AUC', 'AUA', 'AUG', 'GUU',
       'GUC', 'GUA', 'GUG', 'GCU', 'GCC', 'GCA', 'GCG', 'CCU', 'CCC', 'CCA',
       'CCG', 'UGG', 'GGU', 'GGC', 'GGA', 'GGG', 'UCU', 'UCC', 'UCA', 'UCG',
       'AGU', 'AGC', 'ACU', 'ACC', 'ACA', 'ACG', 'UAU', 'UAC', 'CAA', 'CAG',
       'AAU', 'AAC', 'UGU', 'UGC', 'CAU', 'CAC', 'AAA', 'AAG', 'CGU', 'CGC',
       'CGA', 'CGG', 'AGA', 'AGG', 'GAU', 'GAC', 'GAA', 'GAG', 'UAA', 'UAG',
       'UGA'],
      dtype='object')

In [7]:
for col in df.columns:
  unique_values = df[col].unique()
  print(f"{col} ({len(unique_values)} unique)")
  print(unique_values)

Kingdom (11 unique)
['vrl' 'arc' 'bct' 'phg' 'plm' 'pln' 'inv' 'vrt' 'mam' 'rod' 'pri']
DNAtype (11 unique)
[ 0  6  4  2  1  3  7  9  5 11 12]
Ncodons (7103 unique)
[    1995     1474     4862 ...    96254 40662582  8998998]
SpeciesName (13016 unique)
['Epizootic haematopoietic necrosis virus' 'Bohle iridovirus'
 'Sweet potato leaf curl virus' ...
 'mitochondrion Pongo pygmaeus pygmaeus' 'Homo sapiens'
 'mitochondrion Homo sapiens']
UUU (6797 unique)
['0.01654' '0.02714' '0.01974' ... 0.0138 0.01757 0.01778]
UUC (5874 unique)
['0.01203' '0.01357' '0.0218' ... 0.02591 0.03446 0.03555]
UUA (4796 unique)
[0.0005  0.00068 0.01357 ... 0.03671 0.02285 0.04059]
UUG (3282 unique)
[0.00351 0.00678 0.01543 ... 0.0004  0.00491 0.00619]
CUU (3677 unique)
[0.01203 0.00407 0.00782 ... 0.00504 0.0299  0.03415]
CUC (4389 unique)
[0.03208 0.02849 0.01111 ... 0.04792 0.05322 0.05042]
CUA (4063 unique)
[0.001   0.00204 0.01028 ... 0.06849 0.06669 0.07604]
CUG (4562 unique)
[0.0401  0.0441  0.01193 ... 0.

In [10]:
df.isnull().any().any()

np.False_